=== Robcaster92/WSDA2025Project/ProgettoFinaleRobertoCastro/src/main/resources/static/Assignement2/XML/maintainer_status.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Maintainers" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Maintainer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="Nome" minOccurs="1" type="xs:string"/>
                            <xs:element name="Cognome" minOccurs="1" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Robcaster92/WSDA2025Project/ProgettoFinaleRobertoCastro/src/main/resources/static/Assignement2/XML/maintainer_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<Maintainers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="maintainer_status.xsd">
    <Maintainer>
        <ID>1234</ID>
        <Nome>Luca</Nome>
        <Cognome>Rossi</Cognome>
    </Maintainer>

    <Maintainer>
        <ID>4321</ID>
        <Nome>Sara</Nome>
        <Cognome>Verdi</Cognome>
    </Maintainer>

    <Maintainer>
        <ID>1324</ID>
        <Nome>Giorgio</Nome>
        <Cognome>Neri</Cognome>
    </Maintainer>

</Maintainers>
